[package]
name = "sap"
version = "0.1.0"
authors = ["mc1098 <m.cripps1@uni.brighton.ac.uk>"]
edition = "2018"
license = "MIT"

[dependencies]
wasm-bindgen = "0.2.74"

[dev-dependencies]
wasm-bindgen-test = "0.3.24"
yew = { git = "https://github.com/yewstack/yew.git" }


[dependencies.web-sys]
version = "0.3.51"
features = [
	"HtmlImageElement",
	"HtmlLabelElement",
	"InputEvent",
	"InputEventInit",
	"KeyboardEvent",
	"KeyboardEventInit",
	"NodeFilter",
	"NodeList",
	"TreeWalker",
]

[features]
default = []
Yew = []