[package]
name = "sap"
version = "0.1.0"
authors = ["mc1098"]
edition = "2018"
license = "MIT"

[dependencies]
sap-aria = { path = "crates/sap-aria" }
sap-utils = { path = "crates/sap-utils" }
wasm-bindgen = "0.2.74"

[dev-dependencies]
wasm-bindgen-test = "0.3.24"
yew = { git = "https://github.com/yewstack/yew.git" }
sap-yew = { path = "crates/sap-yew" }


[dependencies.web-sys]
version = "0.3.51"
features = [
	"HtmlImageElement",
	"HtmlLabelElement",
	"InputEvent",
	"InputEventInit",
	"KeyboardEvent",
	"KeyboardEventInit",
	"MouseEventInit",
	"NodeFilter",
	"NodeList",
	"TreeWalker",
]

[features]
default = []

[workspace]
# crates to document when using cargo doc
default-members = [
	"../sap",
	"crates/sap-aria",
	"crates/sap-mock",
	"crates/sap-utils",
	"crates/sap-yew",
]
members = [
	"crates/sap-aria",
	"crates/sap-mock",
	"crates/sap-utils",
	"crates/sap-yew",
	"examples/counter",
	"examples/pub_sub",
	"examples/router",
	"examples/todo",
]

[patch.crates-io]
sap-aria = { path = "crates/sap-aria" }
