[package]
name = "yew-testing-lib"
version = "0.1.0"
authors = ["mc1098 <m.cripps1@uni.brighton.ac.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = { path = "../os-projects/yew/packages/yew/" }
# yew = "0.18.0"
wasm-bindgen-test = "0.3.24"
wasm-bindgen = "0.2.74"
web-sys = { version = "0.3.51", features = ['NodeFilter', 'NodeList', 'TreeWalker'] }